language: python

python:
  - 2.7

install:
    # command to upgrade pip
    - pip install --upgrade pip
    # command to install dependencies
    - pip install .
    - sudo pip install flake8

script:
    - flake8 .
    - nosetests openstack_plugin_common:OverLimitRetryProxyTestCase --nologcapture --nocapture
